version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    # command: npm run seed  
    # command: npx typeorm-ts-node-esm migration:generate ./src/migrations/update-post-table -d ./src/datasource.config.ts #only for test
    # command: npx typeorm-ts-node-commonjs migration:run  -d src/datasource.config.ts
            

  adminer:
    build:
      context: ./adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"

volumes:
  postgres-data:
